all: Optimize image layer generation
Optimize the container layers that are built by cleaning up container contents in the same 'RUN' step that
they get generated in. This is due to each 'RUN' step generating their own image layer during container build.

If the contents of an image layer gets removed in a 'RUN' step outside of the step that generates it, the visibility of the removed contents
is gone, but the data still persists due to the final image layer using the 'diffs' of each 'RUN' step (image layer file ghosting/whiteout files).
This means that while a user that launches the container cannot see the removed files, their size is still persistent in the final layer.

This is primarily relevant when wanting to remove and build artifacts or caches that may get created during a build process. The removal of these artifacts or caches should occur within the same 'RUN' step in order for their removal to be reflected properly in the final image.

Signed-off-by: Anderson Chauphan <achauph@sandia.gov>

diff --git a/dockerfiles/clang-openmpi/Dockerfile b/dockerfiles/clang-openmpi/Dockerfile
--- a/dockerfiles/clang-openmpi/Dockerfile
+++ b/dockerfiles/clang-openmpi/Dockerfile
@@ -23,8 +23,10 @@ RUN bash -l -c "spack bootstrap now"
 ARG compiler_version=
 
 RUN bash -l -c "spack compiler find"
-RUN bash -l -c "spack -C /home/runner install --deprecated llvm+llvm_link_dylib+clang+lld${compiler_version} target=x86_64 || true"
-RUN bash -l -c "spack -C /home/runner install --deprecated llvm+llvm_link_dylib+clang+lld${compiler_version} target=x86_64"
+RUN bash -l -c "\
+    (spack -C /home/runner install --deprecated llvm+link_llvm_dylib+clang+lld${compiler_version} target=x86_64 || true) && \
+    spack -C /home/runner install --deprecated llvm+link_llvm_dylib+clang+lld${compiler_version} target=x86_64 && \
+    spack clean --downloads"
 
 ARG mpi_version=
 
@@ -137,14 +139,19 @@ RUN bash -l -c "export FC=\$(type -p gfortran) >> /home/runner/.bashrc"
 RUN bash -l -c "module load llvm && spack compiler find --mixed-toolchain $COMPILER_ROOT"
 
 RUN bash -l -c "spack external find python"
-
 RUN bash -l -c "spack concretize"
-RUN bash -l -c "cd /home/runner && spack env depfile -o Makefile"
-# Just in case a mirror fails to pull, retry the spack install so that we can preserve
-# all of the packages that did build successfully
-RUN bash -l -c "cd /home/runner && make -j6 || true"
-RUN bash -l -c "cd /home/runner && make -j6"
-RUN rm /home/runner/Makefile
+# Export spack environment into a Makefile and run
+# `make` twice to mimic a retry if a pull from spack mirror fails.
+# Perform all the related cleanup under a single RUN to avoid
+# including ghost files in the final image layer.
+RUN bash -l -c " \
+    cd /home/runner && \
+    spack env depfile -o Makefile && \
+    (make -j6 || true) && \
+    make -j6 && \
+    spack clean --downloads && \
+    rm Makefile && \
+    rm -rf .cache"
 
 ENV OMPI_ALLOW_RUN_AS_ROOT=1
 ENV OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
diff --git a/dockerfiles/cuda-gnu-openmpi/Dockerfile b/dockerfiles/cuda-gnu-openmpi/Dockerfile
--- a/dockerfiles/cuda-gnu-openmpi/Dockerfile
+++ b/dockerfiles/cuda-gnu-openmpi/Dockerfile
@@ -26,8 +26,10 @@ RUN bash -l -c "spack bootstrap now"
 ARG compiler_version=
 
 RUN bash -l -c "spack compiler find"
-RUN bash -l -c "spack -C /home/runner install --deprecated gcc${compiler_version} target=x86_64 || true"
-RUN bash -l -c "spack -C /home/runner install --deprecated gcc${compiler_version} target=x86_64"
+RUN bash -l -c " \
+    (spack -C /home/runner install --deprecated gcc${compiler_version} target=x86_64 || true) && \
+    spack -C /home/runner install --deprecated gcc${compiler_version} target=x86_64 && \
+    spack clean --downloads"
 
 RUN bash -l -c "spack module tcl refresh -y"
 RUN rm -rf /home/runner/.spack
@@ -145,13 +147,18 @@ modules:\n\
 RUN echo -e "spack env activate /home/runner/environment\n" >> /home/runner/.bashrc
 
 RUN bash -l -c "spack concretize --force --fresh"
-RUN bash -l -c "cd /home/runner && spack env depfile -o Makefile"
-# Just in case a mirror fails to pull, retry the spack install so that we can preserve
-# all of the packages that did build successfully
-RUN bash -l -c "cd /home/runner && make -j24 || true"
-RUN bash -l -c "cd /home/runner && make -j24 || true"
-RUN bash -l -c "cd /home/runner && make -j24"
-RUN rm /home/runner/Makefile
+# Export spack environment into a Makefile and run
+# `make` twice to mimic a retry if a pull from spack mirror fails.
+# Perform all the related cleanup under a single RUN to avoid
+# including ghost files in the final image layer.
+RUN bash -l -c " \
+    cd /home/runner && \
+    spack env depfile -o Makefile && \
+    (make -j24 || true) && \
+    make -j24 && \
+    spack clean --downloads && \
+    rm Makefile && \
+    rm -rf .cache"
 
 ENV OMPI_ALLOW_RUN_AS_ROOT=1
 ENV OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
diff --git a/dockerfiles/gnu-ubi10/Dockerfile b/dockerfiles/gnu-ubi10/Dockerfile
--- a/dockerfiles/gnu-ubi10/Dockerfile
+++ b/dockerfiles/gnu-ubi10/Dockerfile
@@ -23,8 +23,10 @@ RUN bash -l -c "spack bootstrap now"
 ARG compiler_version=
 
 RUN bash -l -c "spack compiler find"
-RUN bash -l -c "spack -C /home/runner install --deprecated gcc${compiler_version} target=x86_64 || true"
-RUN bash -l -c "spack -C /home/runner install --deprecated gcc${compiler_version} target=x86_64"
+RUN bash -l -c "\
+    (spack -C /home/runner install --deprecated gcc${compiler_version} target=x86_64 || true) && \
+    spack -C /home/runner install --deprecated gcc${compiler_version} target=x86_64 && \
+    spack clean --downloads"
 
 RUN mkdir /home/runner/environment
 # Consider using here-documents once we get to Buildah 1.33.0+
@@ -136,12 +138,18 @@ RUN bash -l -c "echo \"export MODULEPATH=/home/runner/spack/share/spack/modules/
 RUN bash -l -c "module load gcc && spack compiler find $COMPILER_ROOT"
 
 RUN bash -l -c "spack concretize"
-RUN bash -l -c "cd /home/runner && spack env depfile -o Makefile"
-# Just in case a mirror fails to pull, retry the spack install so that we can preserve
-# all of the packages that did build successfully
-RUN bash -l -c "cd /home/runner && make -j6 || true"
-RUN bash -l -c "cd /home/runner && make -j6"
-RUN rm /home/runner/Makefile
+# Export spack environment into a Makefile and run
+# `make` twice to mimic a retry if a pull from spack mirror fails.
+# Perform all the related cleanup under a single RUN to avoid
+# including ghost files in the final image layer.
+RUN bash -l -c " \
+    cd /home/runner && \
+    spack env depfile -o Makefile && \
+    (make -j6 || true) && \
+    make -j6 && \
+    spack clean --downloads && \
+    rm Makefile && \
+    rm -rf .cache"
 
 CMD [ "/bin/bash" ]
 
diff --git a/dockerfiles/python/Dockerfile b/dockerfiles/python/Dockerfile
--- a/dockerfiles/python/Dockerfile
+++ b/dockerfiles/python/Dockerfile
@@ -117,12 +117,18 @@ RUN bash -l -c "spack compiler find $COMPILER_ROOT"
 
 
 RUN bash -l -c "spack concretize"
-RUN bash -l -c "cd /home/runner && spack env depfile -o Makefile"
-# Just in case a mirror fails to pull, retry the spack install so that we can preserve
-# all of the packages that did build successfully
-RUN bash -l -c "cd /home/runner && make -j6 || true"
-RUN bash -l -c "cd /home/runner && make -j6"
-RUN rm /home/runner/Makefile
+# Export spack environment into a Makefile and run
+# `make` twice to mimic a retry if a pull from spack mirror fails.
+# Perform all the related cleanup under a single RUN to avoid
+# including ghost files in the final image layer.
+RUN bash -l -c " \
+    cd /home/runner && \
+    spack env depfile -o Makefile && \
+    (make -j6 || true) && \
+    make -j6 && \
+    spack clean --downloads && \
+    rm Makefile && \
+    rm -rf .cache"
 
 CMD [ "/bin/bash" ]
 
